project_id = "uftfqhpragdpjsixqqrc"

[functions.meta-store-token]
verify_jwt = false

[functions.meta-sync-assets]
verify_jwt = false

[functions.meta-oauth-url]
verify_jwt = false

[functions.meta-oauth-callback]
verify_jwt = false

[functions.meta-list-campaigns]
verify_jwt = false